#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# jScript_durationEstimator
# Outputs estimated duration of each line
# ver. 1: September 28, 2020
# (c) Oki Mikito, 2020. All rights reserved.

import sys, codecs, os
from pykakasi import kakasi

fName = sys.argv[1]
jFileBuffer = ''
jBufferArray = []
outBuffer = ''


try:
    jFile = codecs.open(fName, 'r', 'utf_8')
    jFileBuffer = jFile.read()
    jFile.close()
except IOError:
    print('ERROR: The specified file cannot be accessed.\nSelect a valid text file and try again.\nExiting...')
    sys.exit(0)

kakasi = kakasi()

kakasi.setMode('H', None)
kakasi.setMode('K', None)
kakasi.setMode('J', 'H')

conv = kakasi.getConverter()

jBufferArray = jFileBuffer.split('\n')

for i in jBufferArray:
    iArray = []
    iArray.append(i)
    iBuf = conv.do(i)
    if (len(i)==0):
        iArray.append('-')
    else:
        iArray.append(str(round(len(iBuf) *  0.12718685831622, 2)) + ' sec.')
    outBuffer += iArray[0] + '\t' + iArray[1] + '\n'

outBuffer = outBuffer[:-1]
print(outBuffer)

