#!/usr/bin/env python3

import os, sys, re

fileListArray = os.listdir(os.getcwd())
fNameModifier = re.compile('\.wav$')
fName = ''
numberofFiles = sys.argv[1]
newFiles = ''

for f in fileListArray:
    if f.find('.wav') > 0:
        fName = f

fName = fNameModifier.sub('', fName)

for i in range(int(numberofFiles)):
    newFiles = newFiles + fName + '_JA_' + str(i+1).zfill(2) + '.wav\n'

newFiles = newFiles[:-1]

try:
    t = open('fList_' + str(numberofFiles) + 'files.txt', 'w')
    t.write(newFiles)
    t.close()
except IOError:
    print('ERROR while writing. Exiting...')
    sys.exit(0)


